server:
  port: ${CONSUMER_PORT:8081}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:dubbo-consumer-2}
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://${NACOS_HOST:127.0.0.1}:8848
    discovery-mode: application
  metadata-report:
    address: nacos://${NACOS_HOST:127.0.0.1}:8848
    cache-file: ./.dubbo/${spring.application.name}/consumer-metadata.cache