server:
  port: ${PROVIDE_SERVICE:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:dubbo-provider-1}

dubbo:
  application:
    name: ${spring.application.name}
  cache:
    base-path: ./.dubbo/${spring.application.name}
    file:
      enable: true
  protocol:
    name: dubbo
    port: ${protocol.port:20880}
  registry:
    address: nacos://${NACOS_HOST:127.0.0.1}:8848
    register-mode: instance
    register-all: true
  metadata-report:
    address: nacos://${NACOS_HOST:127.0.0.1}:8848
    cache-file: ${user.home}/.dubbo/${spring.application.name}/metadata.cache
    report-mode: remote
    sync-report: true
  metadata:
    service-exposure: true
    export: true